//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// 此源代码由 wsdl 自动生成, Version=4.0.30319.33440。
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="InternalSvcSoap", Namespace="http://tempuri.org/")]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(object[]))]
public partial class InternalClt : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback InvokeBLLOperationCompleted;

    private static System.Runtime.Serialization.Formatters.Binary.BinaryFormatter _bf = new System.Runtime.Serialization.Formatters.Binary.BinaryFormatter();
    
    /// <remarks/>
    public InternalClt() {
        this.Url = "http://localhost/ksm/InternalSvc.asmx";
    }
    
    /// <remarks/>
    public event InvokeBLLCompletedEventHandler InvokeBLLCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InvokeBLL", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public object InvokeBLL(string typeName, string methodName, object[] para) {
        object[] results = this.Invoke("InvokeBLL", new object[] {
                    typeName,
                    methodName,
                    para});
        if (results[0] is Byte[])
        {
            return _bf.Deserialize(new System.IO.MemoryStream(results[0] as Byte[]));
        }
        else
        { return results[0]; }

        
        //return ((object)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginInvokeBLL(string typeName, string methodName, object[] para, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("InvokeBLL", new object[] {
                    typeName,
                    methodName,
                    para}, callback, asyncState);
    }
    
    /// <remarks/>
    public object EndInvokeBLL(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((object)(results[0]));
    }
    
    /// <remarks/>
    public void InvokeBLLAsync(string typeName, string methodName, object[] para) {
        this.InvokeBLLAsync(typeName, methodName, para, null);
    }
    
    /// <remarks/>
    public void InvokeBLLAsync(string typeName, string methodName, object[] para, object userState) {
        if ((this.InvokeBLLOperationCompleted == null)) {
            this.InvokeBLLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInvokeBLLOperationCompleted);
        }
        this.InvokeAsync("InvokeBLL", new object[] {
                    typeName,
                    methodName,
                    para}, this.InvokeBLLOperationCompleted, userState);
    }
    
    private void OnInvokeBLLOperationCompleted(object arg) {
        if ((this.InvokeBLLCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.InvokeBLLCompleted(this, new InvokeBLLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void InvokeBLLCompletedEventHandler(object sender, InvokeBLLCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class InvokeBLLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal InvokeBLLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public object Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((object)(this.results[0]));
        }
    }
}
